### ISSUE TITLE
Private Key generation flow using BIP39 mnemonic 

### ISSUE THREAD

**Issue by jcksncllwy** [dsys/multi-desktop#7]
**As a** Multi-desktop user
**I want to** walk through the steps of key generation
**So that I** can write down my backup mnemonic for recovery

---

Already got basic private key generation working. Currently working on a React flow to generate key using BIP 39 mnemonic and prompt user to securely store mnemonic for key recovery.

**Comment by kern** [comment]
BIP 39 (12-word mneumonics, well-known dictionary, last word is a checksum)

using generated mneumonic (BIP 32/44) by specifying "paths" to private keys

we'll use a standardized path: "m/44'/60'/0'/0/"

**Comment by kern** [comment]
storing priv/pub keys in pouchdb

**Comment by jcksncllwy** [comment]
This is almost done. Actual mnemonic and key generation is working great. Just need to wrap up the UI flow.
